### ISSUE TITLE
typo in script - version 0.4.2 -> 0.4.3 in vmware.SRM module

### ISSUE THREAD

**Issue by AGH2021** [AsBuiltReport/AsBuiltReport.VMware.SRM#23]
### Bug description

Unable to import Function due to error in expression 
Note the S in 0.4.3 version at the end of ColumnWidths

Get-AbrSRMRecoveryPlan
        Version:        0.4.3                                                                              =>     
                                                         ColumnWidths = 16, 10, 12, 12, 12, 12, 12, 14s         =>           
        Version:        0.4.0                                                                              <=           
                                                    ColumnWidths = 16, 10, 12, 12, 12, 12, 12, 14          <=     

### Command-line input

import-module asbuiltreport.vmware.srm

### Steps to reproduce

import-module asbuiltreport.vmware.srm

### Expected behaviour

successful load

### Operating System

Windows Server 2022

### PowerShell Version

Name                           Value                                                                                                                                          
----                           -----                                                                                                                                          
PSVersion                      5.1.20348.1850                                                                                                                                 
PSEdition                      Desktop                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                        
BuildVersion                   10.0.20348.1850                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                
WSManStackVersion              3.0                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                            
SerializationVersion           1.1.0.1  

### PowerShell Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.0      AsBuiltReport.Core                  {New-AsBuiltReport, New-AsBuiltConfig, New-AsBuiltReportConfig}
Script     0.4.3      AsBuiltReport.VMware.SRM            Invoke-AsBuiltReport.VMware.SRM
Script     0.4.2      AsBuiltReport.VMware.SRM            Invoke-AsBuiltReport.VMware.SRM
Script     1.3.3.1    AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.VMware.SRM/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
There is something wrong with this function. I will delay the release until I validate what is wrong.
